stages:
  prepare:
    cmd: python datasets/MovieLens_Large/preprocess_ml1m.py
    deps:
    - datasets/MovieLens_Large/ml-1m.txt
    - datasets/MovieLens_Large/preprocess_ml1m.py
    outs:
    - datasets/MovieLens_Large/dataset_stats.json
    - datasets/MovieLens_Large/test
    - datasets/MovieLens_Large/train
    - datasets/MovieLens_Large/val
  train:
    cmd: python scripts/train.py 
      --config=recsys_project/configs/config_sasrec.py 
      --config_hyper=recsys_project/configs/config_training.py
    deps:
    - recsys_project/configs/config.py
    - recsys_project/configs/config_sasrec.py
    - recsys_project/configs/config_training.py
    - recsys_project/utils/training_utils.py
    - scripts/train.py
    outs:
    - checkpoints
    - hf_checkpoints
  evaluate:
    cmd: python scripts/evaluate.py 
      --config=recsys_project/configs/config_sasrec.py 
      --config_hyper=recsys_project/configs/config_training.py 
      --checkpoint=checkpoints/best_model.pt
    deps:
    - recsys_project/configs/config.py
    - recsys_project/configs/config_sasrec.py
    - recsys_project/configs/config_training.py
    - recsys_project/utils/evaluation_utils.py
    - scripts/evaluate.py
